/**
 * Token Cost Constants and Calculation
 *
 * This module provides pricing constants and cost calculation utilities
 * for tracking API usage costs across Claude model sessions.
 *
 * Token costs are essential for:
 * - Budgeting and cost monitoring
 * - Optimizing prompts for cost efficiency
 * - Providing users with usage transparency
 * - Making informed decisions about model selection
 *
 * Pricing is based on Anthropic's published rates and should be
 * updated when pricing changes occur.
 *
 * @see https://www.anthropic.com/api for current pricing
 */

/**
 * Token pricing structure for a single model.
 *
 * Prices are expressed in USD per 1 million tokens (MTok),
 * following Anthropic's standard pricing format.
 */
export interface ModelPricing {
  /**
   * Cost in USD per 1 million input tokens.
   * Input tokens include system prompts, conversation history, and user messages.
   */
  inputPerMTok: number;

  /**
   * Cost in USD per 1 million output tokens.
   * Output tokens are the content generated by the model.
   */
  outputPerMTok: number;
}

/**
 * Supported Claude model identifiers.
 *
 * These correspond to the model IDs used in Anthropic API calls.
 * New models should be added here as they become available.
 */
export type ClaudeModel =
  | 'claude-3-opus-20240229'
  | 'claude-3-sonnet-20240229'
  | 'claude-3-haiku-20240307'
  | 'claude-3-5-sonnet-20240620'
  | 'claude-3-5-sonnet-20241022'
  | 'claude-3-5-haiku-20241022';

/**
 * Token cost constants for Claude models.
 *
 * Pricing in USD per 1 million tokens (MTok).
 * These values are based on Anthropic's published pricing as of 2024.
 *
 * Note: Pricing may change over time. Update these values when
 * Anthropic announces pricing changes.
 *
 * @example
 * ```typescript
 * // Get pricing for Claude 3.5 Sonnet
 * const pricing = TOKEN_COSTS['claude-3-5-sonnet-20241022'];
 * console.log(`Input: $${pricing.inputPerMTok}/MTok`);
 * console.log(`Output: $${pricing.outputPerMTok}/MTok`);
 * ```
 */
export const TOKEN_COSTS: Record<ClaudeModel, ModelPricing> = {
  // Claude 3 Opus - Most capable, highest cost
  'claude-3-opus-20240229': {
    inputPerMTok: 15.0,
    outputPerMTok: 75.0,
  },

  // Claude 3 Sonnet - Balanced performance and cost
  'claude-3-sonnet-20240229': {
    inputPerMTok: 3.0,
    outputPerMTok: 15.0,
  },

  // Claude 3 Haiku - Fast and cost-effective
  'claude-3-haiku-20240307': {
    inputPerMTok: 0.25,
    outputPerMTok: 1.25,
  },

  // Claude 3.5 Sonnet (June 2024) - Improved Sonnet
  'claude-3-5-sonnet-20240620': {
    inputPerMTok: 3.0,
    outputPerMTok: 15.0,
  },

  // Claude 3.5 Sonnet (October 2024) - Latest Sonnet
  'claude-3-5-sonnet-20241022': {
    inputPerMTok: 3.0,
    outputPerMTok: 15.0,
  },

  // Claude 3.5 Haiku - Fast and efficient
  'claude-3-5-haiku-20241022': {
    inputPerMTok: 1.0,
    outputPerMTok: 5.0,
  },
};

/**
 * Calculates the cost in USD for a given number of tokens.
 *
 * This function computes the total API cost based on the model used
 * and the number of input/output tokens consumed during a session.
 *
 * @param model - The Claude model identifier
 * @param inputTokens - Number of input tokens (prompts, context, user messages)
 * @param outputTokens - Number of output tokens (model responses)
 * @returns Total cost in USD, rounded to 6 decimal places for precision
 *
 * @throws {Error} If the model is not recognized in TOKEN_COSTS
 *
 * @example
 * ```typescript
 * // Calculate cost for a typical session
 * const cost = calculateCost(
 *   'claude-3-5-sonnet-20241022',
 *   2500,  // input tokens
 *   1800   // output tokens
 * );
 * console.log(`Session cost: $${cost.toFixed(4)}`);
 * // Output: "Session cost: $0.0345"
 * ```
 *
 * @example
 * ```typescript
 * // Compare costs between models
 * const inputTokens = 5000;
 * const outputTokens = 3000;
 *
 * const haikuCost = calculateCost('claude-3-5-haiku-20241022', inputTokens, outputTokens);
 * const sonnetCost = calculateCost('claude-3-5-sonnet-20241022', inputTokens, outputTokens);
 *
 * console.log(`Haiku: $${haikuCost.toFixed(4)}, Sonnet: $${sonnetCost.toFixed(4)}`);
 * ```
 */
export function calculateCost(
  model: ClaudeModel,
  inputTokens: number,
  outputTokens: number
): number {
  const pricing = TOKEN_COSTS[model];

  if (!pricing) {
    throw new Error(
      `Unknown model: ${model}. Available models: ${Object.keys(TOKEN_COSTS).join(', ')}`
    );
  }

  // Convert from per-million-token pricing to actual cost
  // Formula: (tokens / 1,000,000) * pricePerMTok
  const inputCost = (inputTokens / 1_000_000) * pricing.inputPerMTok;
  const outputCost = (outputTokens / 1_000_000) * pricing.outputPerMTok;

  // Round to 6 decimal places for precision (sub-cent accuracy)
  const totalCost = inputCost + outputCost;
  return Math.round(totalCost * 1_000_000) / 1_000_000;
}
